# Form implementation generated from reading ui file 'diagram.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Formp(object):
    def setupUi(self, Formp):
        Formp.setObjectName("Formp")
        Formp.resize(240, 100)
        Formp.setMinimumSize(QtCore.QSize(240, 100))
        Formp.setMaximumSize(QtCore.QSize(240, 100))
        Formp.setStyleSheet("QWidget {\n"
"    color: #E0FBFC;\n"
"    background-color: #1b2022;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Formp)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stolb = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.stolb.setMaximumSize(QtCore.QSize(16777215, 17))
        self.stolb.setObjectName("stolb")
        self.verticalLayout.addWidget(self.stolb)
        self.add1 = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.add1.setObjectName("add1")
        self.verticalLayout.addWidget(self.add1)
        self.conclusion = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conclusion.sizePolicy().hasHeightForWidth())
        self.conclusion.setSizePolicy(sizePolicy)
        self.conclusion.setMaximumSize(QtCore.QSize(158, 16777215))
        self.conclusion.setObjectName("conclusion")
        self.verticalLayout.addWidget(self.conclusion)

        self.retranslateUi(Formp)
        QtCore.QMetaObject.connectSlotsByName(Formp)

    def retranslateUi(self, Formp):
        _translate = QtCore.QCoreApplication.translate
        Formp.setWindowTitle(_translate("Formp", "Form"))
        self.stolb.setText(_translate("Formp", "Столбец"))
        self.conclusion.setText(_translate("Formp", "Вывод диаграммы"))
